<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- 	
		Appendere le seguenti stringhe 
		nel file ..\WEB-INF\classes\project_translations.inc
		PRIMA del tag </TRANSLATED_STRINGS>
  -->

<Orig_str>Attività in Attesa</Orig_str>
	<ITA>Attività Da Sviluppare</ITA>
	<ENG>To be developed Task</ENG>
	<ESP>To be developed Task</ESP>
	<DEU>To be developed Task</DEU>
	<FRA>To be developed Task</FRA>
<Orig_str>In Attesa</Orig_str>
	<ITA>Da Sviluppare</ITA>
	<ENG>To develop</ENG>
	<ESP>To develop</ESP>
	<DEU>To develop</DEU>
	<FRA>To develop</FRA>
<Orig_str>Da Sviluppare</Orig_str>
	<ITA>Da Sviluppare</ITA>
	<ENG>To develop</ENG>
	<ESP>To develop</ESP>
	<DEU>To develop</DEU>
	<FRA>To develop</FRA>
<Orig_str>Attività da Confermare</Orig_str>
	<ITA>Attività In Attesa</ITA>
	<ENG>Waiting Task</ENG>
	<ESP>Waiting Task</ESP>
	<DEU>Waiting Task</DEU>
	<FRA>Waiting Task</FRA>
<Orig_str>Da Confermare</Orig_str>
	<ITA>In Attesa</ITA>
	<ENG>Waiting</ENG>
	<ESP>Waiting</ESP>
	<DEU>Waiting</DEU>
	<FRA>Waiting</FRA>
<Orig_str>ATTIVITA ANNULLATA. Titolo</Orig_str>
    <ITA>ATTIVITA SOSPESA. Titolo</ITA>
	<ENG>SUSPENDED TASK. Title</ENG>
	<ESP>SUSPENDED TASK. Title</ESP>
	<DEU>SUSPENDED TASK. Title</DEU>
	<FRA>SUSPENDED TASK. Title</FRA>
<Orig_str>Annullata</Orig_str>
	<ITA>Sospesa</ITA>
	<ENG>Suspended</ENG>
	<ESP>Suspended</ESP>
	<DEU>Suspended</DEU>
	<FRA>Suspended</FRA>
<Orig_str>Sospesa</Orig_str>
	<ITA>Sospesa</ITA>
	<ENG>Suspended</ENG>
	<ESP>Suspended</ESP>
	<DEU>Suspended</DEU>
	<FRA>Suspended</FRA>
<Orig_str>Attività Annullata</Orig_str>
	<ITA>Attività Sospesa</ITA>
	<ENG>Suspended Task</ENG>
	<ESP>Suspended Task</ESP>
	<DEU>Suspended Task</DEU>
	<FRA>Suspended Task</FRA>
<Orig_str>Attività annullata</Orig_str>
	<ITA>Attività Sospesa</ITA>
	<ENG>Suspended Task</ENG>
	<ESP>Suspended Task</ESP>
	<DEU>Suspended Task</DEU>
	<FRA>Suspended Task</FRA>
<Orig_str>ATTIVITA COMPLETATA. Titolo</Orig_str>
    <ITA>ATTIVITA SVILUPPATA. Titolo</ITA>
	<ENG>DEVELOPED TASK. Title</ENG>
	<ESP>DEVELOPED TASK. Title</ESP>
	<DEU>DEVELOPED TASK. Title</DEU>
	<FRA>DEVELOPED TASK. Title</FRA>
<Orig_str>Attività Completata</Orig_str>
	<ITA>Attività Sviluppata</ITA>
	<ENG>Developed Task</ENG>
	<ESP>Developed Task</ESP>
	<DEU>Developed Task</DEU>
	<FRA>Developed Task</FRA>
<Orig_str>Attività completata</Orig_str>
    <ITA>Attività completata</ITA>
    <ENG>Developed Task</ENG>
    <ESP>Developed Task</ESP>
    <FRA>Developed Task</FRA>
    <DEU>Developed Task</DEU>
<Orig_str>Completata</Orig_str>
	<ITA>Sviluppata</ITA>
	<ENG>Developed</ENG>
	<ESP>Developed</ESP>
	<DEU>Developed</DEU>
	<FRA>Developed</FRA>
<Orig_str>Sviluppata</Orig_str>
	<ITA>Sviluppata</ITA>
	<ENG>Developed</ENG>
	<ESP>Developed</ESP>
	<DEU>Developed</DEU>
	<FRA>Developed</FRA>
<Orig_str>Attività Confermata</Orig_str>
	<ITA>Attività In Sviluppo</ITA>
	<ENG>Developing Task</ENG>
	<ESP>Developing Task</ESP>
	<DEU>Developing Task</DEU>
	<FRA>Developing Task</FRA>
<Orig_str>Confermata</Orig_str>
	<ENG>Developing</ENG>
	<ESP>Developing</ESP>
	<DEU>Developing</DEU>
	<FRA>Developing</FRA>
<Orig_str>Attività Confermata</Orig_str>
	<ITA>Attività In Sviluppo</ITA>
	<ENG>Developing Task</ENG>
	<ESP>Developing Task</ESP>
	<DEU>Developing Task</DEU>
	<FRA>Developing Task</FRA>
<Orig_str>Confermata</Orig_str>
	<ITA>In Sviluppo</ITA>
	<ENG>Developing</ENG>
	<ESP>Developing</ESP>
	<DEU>Developing</DEU>
	<FRA>Developing</FRA>
<Orig_str>In Sviluppo</Orig_str>
	<ITA>In Sviluppo</ITA>
	<ENG>Developing</ENG>
	<ESP>Developing</ESP>
	<DEU>Developing</DEU>
	<FRA>Developing</FRA>
<Orig_str>Rifare Strutturale</Orig_str>
	<ITA>Rifare Strutturale</ITA>
	<ENG>Structural remake</ENG>
	<ESP>Structural remake</ESP>
	<DEU>Structural remake</DEU>
	<FRA>Structural remake</FRA>
<Orig_str>Creazione Articolo</Orig_str>
	<ITA>Creazione Articolo</ITA>
	<ENG>Item Creation</ENG>
	<ESP>Item Creation</ESP>
	<DEU>Item Creation</DEU>
	<FRA>Item Creation</FRA>
<Orig_str>Assegnazione Offerte</Orig_str>
	<ITA>Assegnazione Offerte</ITA>
	<ENG>Offers Assignment</ENG>
	<ESP>Offers Assignment</ESP>
	<DEU>Offers Assignment</DEU>
	<FRA>Offers Assignment</FRA>
<Orig_str>Assegnazione Ordini</Orig_str>
	<ITA>Assegnazione Ordini</ITA>
	<ENG>Orders Assignment</ENG>
	<ESP>Orders Assignment</ESP>
	<DEU>Orders Assignment</DEU>
	<FRA>Orders Assignment</FRA>
<Orig_str>Strutturisti</Orig_str>
	<ITA>Strutturisti</ITA>
	<ENG>Structural Engeneers</ENG>
	<ESP>Structural Engeneers</ESP>
	<DEU>Structural Engeneers</DEU>
	<FRA>Structural Engeneers</FRA>
<Orig_str>Configura nuova offerta</Orig_str>
	<ITA>Configura nuova offerta</ITA>
	<ENG>New offer configuration</ENG>
	<ESP>New offer configuration</ESP>
	<DEU>New offer configuration</DEU>
	<FRA>New offer configuration</FRA>
<Orig_str>Configura nuovo ordine</Orig_str>
	<ITA>Configura nuovo ordine</ITA>
	<ENG>New order configuration</ENG>
	<ESP>New order configuration</ESP>
	<DEU>New order configuration</DEU>
	<FRA>New order configuration</FRA>
<Orig_str>Incrementa Versione Offerta</Orig_str>
	<ITA>Incrementa Versione Offerta</ITA>
	<ENG>Offer Version Increment</ENG>
	<ESP>Offer Version Increment</ESP>
	<DEU>Offer Version Increment</DEU>
	<FRA>Offer Version Increment</FRA>
<Orig_str>Incrementa Versione Ordine</Orig_str>
	<ITA>Incrementa Versione Ordine</ITA>
	<ENG>Order Version Increment</ENG>
	<ESP>Order Version Increment</ESP>
	<DEU>Order Version Increment</DEU>
	<FRA>Order Version Increment</FRA>
<Orig_str>Configura Ordine</Orig_str>
	<ITA>Configura Ordine</ITA>
	<ENG>Order Configuration</ENG>
	<ESP>Order Configuration</ESP>
	<DEU>Order Configuration</DEU>
	<FRA>Order Configuration</FRA>
<Orig_str>TRATTATIVA</Orig_str>
	<ITA>TRATTATIVA</ITA>
	<ENG>NEGOTIATION</ENG>
	<ESP>NEGOTIATION</ESP>
	<DEU>NEGOTIATION</DEU>
	<FRA>NEGOTIATION</FRA>
<Orig_str>TRATTATIVE</Orig_str>
	<ITA>TRATTATIVE</ITA>
	<ENG>NEGOTIATIONS</ENG>
	<ESP>NEGOTIATIONS</ESP>
	<DEU>NEGOTIATIONS</DEU>
	<FRA>NEGOTIATIONS</FRA>
<Orig_str>Trattative</Orig_str>
	<ITA>Trattative</ITA>
	<ENG>Negotiations</ENG>
	<ESP>Negotiations</ESP>
	<DEU>Negotiations</DEU>
	<FRA>Negotiations</FRA>
<Orig_str>Data Entrata UT dal</Orig_str>
	<ITA>Data Entrata UT dal</ITA>
	<ENG>Entry Date UT from</ENG>
	<ESP>Entry Date UT from</ESP>
	<DEU>Entry Date UT from</DEU>
	<FRA>Entry Date UT from</FRA>
<Orig_str>Data Entrata UT</Orig_str>
	<ITA>Data Entrata UT</ITA>
	<ENG>Entry Date UT</ENG>
	<ESP>Entry Date UT</ESP>
	<DEU>Entry Date UT</DEU>
	<FRA>Entry Date UT</FRA>
<Orig_str>Data Uscita UT al</Orig_str>
	<ITA>Data Uscita UT al</ITA>
	<ENG>Release Date UT to</ENG>
	<ESP>Release Date UT to</ESP>
	<DEU>Release Date UT to</DEU>
	<FRA>Release Date UT to</FRA>
<Orig_str>Data Uscita UT dal</Orig_str>
	<ITA>Data Uscita UT dal</ITA>
	<ENG>Release Date UT from</ENG>
	<ESP>Release Date UT from</ESP>
	<DEU>Release Date UT from</DEU>
	<FRA>Release Date UT from</FRA>
<Orig_str>Data UscitaUT al</Orig_str>
	<ITA>Data UscitaUT al</ITA>
	<ENG>Release Date UT to</ENG>
	<ESP>Release Date UT to</ESP>
	<DEU>Release Date UT to</DEU>
	<FRA>Release Date UT to</FRA>
<Orig_str>Service</Orig_str>
	<ITA>Service</ITA>
	<ENG>Service</ENG>
	<ESP>Service</ESP>
	<DEU>Service</DEU>
	<FRA>Service</FRA>
<Orig_str>Stato UT</Orig_str>
	<ITA>Stato UT</ITA>
	<ENG>UT Status</ENG>
	<ESP>UT Status</ESP>
	<DEU>UT Status</DEU>
	<FRA>UT Status</FRA>
<Orig_str>Causa Attesa</Orig_str>
	<ITA>Causa Attesa</ITA>
	<ENG>Waiting Causal</ENG>
	<ESP>Waiting Causal</ESP>
	<DEU>Waiting Causal</DEU>
	<FRA>Waiting Causal</FRA>
<Orig_str>Data Uscita</Orig_str>
	<ITA>Data Uscita</ITA>
	<ENG>Release Date</ENG>
	<ESP>Release Date</ESP>
	<DEU>Release Date</DEU>
	<FRA>Release Date</FRA>
<Orig_str>Ore stimate</Orig_str>
	<ITA>Ore Stimate</ITA>
	<ENG>Estimated Hours</ENG>
	<ESP>Estimated Hours</ESP>
	<DEU>Estimated Hours</DEU>
	<FRA>Estimated Hours</FRA>
<Orig_str>Uscita stimata</Orig_str>
	<ITA>Uscita Stimata</ITA>
	<ENG>Estimated Release</ENG>
	<ESP>Estimated Release</ESP>
	<DEU>Estimated Release</DEU>
	<FRA>Estimated Release</FRA>
<Orig_str>Prodotto x zincatura</Orig_str>
	<ITA>Prodotto x zincatura</ITA>
	<ENG>Galvanizing Product</ENG>
	<ESP>Galvanizing Product</ESP>
	<DEU>Galvanizing Product</DEU>
	<FRA>Galvanizing Product</FRA>
<Orig_str>Tipo Flusso</Orig_str>
	<ITA>Tipo Flusso</ITA>
	<ENG>Flow Type</ENG>
	<ESP>Flow Type</ESP>
	<DEU>Flow Type</DEU>
	<FRA>Flow Type</FRA>
<Orig_str>Rich Cert EN1090</Orig_str>
	<ITA>Rich Cert EN1090</ITA>
	<ENG>Cert Req EN1090</ENG>
	<ESP>Cert Req EN1090</ESP>
	<DEU>Cert Req EN1090</DEU>
	<FRA>Cert Req EN1090</FRA>
<Orig_str>App Cert EN1090</Orig_str>
	<ITA>App Cert EN1090</ITA>
	<ENG>App Cert EN1090</ENG>
	<ESP>App Cert EN1090</ESP>
	<DEU>App Cert EN1090</DEU>
	<FRA>App Cert EN1090</FRA>
<Orig_str>Rich Cert EN15512</Orig_str>
	<ITA>Rich Cert EN15512</ITA>
	<ENG>Cert Req EN15512</ENG>
	<ESP>Cert Req EN15512</ESP>
	<DEU>Cert Req EN15512</DEU>
	<FRA>Cert Req EN15512</FRA>
<Orig_str>App Cert EN15512</Orig_str>
	<ITA>App Cert EN15512</ITA>
	<ENG>App Cert EN15512</ENG>
	<ESP>App Cert EN15512</ESP>
	<DEU>App Cert EN15512</DEU>
	<FRA>App Cert EN15512</FRA>
<Orig_str>(lunghezza x altezza x profondità)</Orig_str>
	<ITA>(lunghezza x altezza x profondità)</ITA>
	<ENG>(lunghezza x altezza x profondità)</ENG>
	<ESP>(length x height x depth)</ESP>
	<DEU>(length x height x depth)</DEU>
	<FRA>(length x height x depth)</FRA>
<Orig_str>Peso (kg):</Orig_str>
	<ITA>Peso (kg):</ITA>
	<ENG>Weight (kg):</ENG>
	<ESP>Weight (kg):</ESP>
	<DEU>Weight (kg):</DEU>
	<FRA>Weight (kg):</FRA>
<Orig_str>Dimensioni (m):</Orig_str>
	<ITA>Dimensioni (m):</ITA>
	<ENG>Dimensions (m):</ENG>
	<ESP>Dimensions (m):</ESP>
	<DEU>Dimensions (m):</DEU>
	<FRA>Dimensions (m):</FRA>
<Orig_str>POSA</Orig_str>
	<ITA>POSA</ITA>
	<ENG>BUILDING</ENG>
	<ESP>BUILDING</ESP>
	<DEU>BUILDING</DEU>
	<FRA>BUILDING</FRA>
<Orig_str>RESA</Orig_str>
	<ITA>RESA</ITA>
	<ENG>RETURN</ENG>
	<ESP>RETURN</ESP>
	<DEU>RETURN</DEU>
	<FRA>RETURN</FRA>
<Orig_str>DATA DISPONIBILITA'</Orig_str>
	<ITA>DATA DISPONIBILITA'</ITA>
	<ENG>AVAILABILITY DATE</ENG>
	<ESP>AVAILABILITY DATE</ESP>
	<DEU>AVAILABILITY DATE</DEU>
	<FRA>AVAILABILITY DATE</FRA>
<Orig_str>DATA SCHEDULATA</Orig_str>
	<ITA>DATA SCHEDULATA</ITA>
	<ENG>SCHEDULED DATE</ENG>
	<ESP>SCHEDULED DATE</ESP>
	<DEU>SCHEDULED DATE</DEU>
	<FRA>SCHEDULED DATE</FRA>
<Orig_str>DATA CONFERMA ORDINE</Orig_str>
	<ITA>DATA CONFERMA ORDINE</ITA>
	<ENG>CONFIRM ORDER DATE</ENG>
	<ESP>CONFIRM ORDER DATE</ESP>
	<DEU>CONFIRM ORDER DATE</DEU>
	<FRA>CONFIRM ORDER DATE</FRA>
<Orig_str>DATA CONFERMA</Orig_str>
	<ITA>DATA CONFERMA</ITA>
	<ENG>CONFIRM DATE</ENG>
	<ESP>CONFIRM DATE</ESP>
	<DEU>CONFIRM DATE</DEU>
	<FRA>CONFIRM DATE</FRA>
<Orig_str>STATO</Orig_str>
	<ITA>STATO</ITA>
	<ENG>STATUS</ENG>
	<ESP>STATUS</ESP>
	<DEU>STATUS</DEU>
	<FRA>STATUS</FRA>
<Orig_str>Stato</Orig_str>
	<ITA>Stato</ITA>
	<ENG>Status</ENG>
	<ESP>Status</ESP>
	<DEU>Status</DEU>
	<FRA>Status</FRA>
<Orig_str>DATA ORDINE</Orig_str>
	<ITA>DATA ORDINE</ITA>
	<ENG>ORDER DATE</ENG>
	<ESP>ORDER DATE</ESP>
	<DEU>ORDER DATE</DEU>
	<FRA>ORDER DATE</FRA>
<Orig_str>NUM. SOTTOCOMMESSA</Orig_str>
	<ITA>NUM. SOTTOCOMMESSA</ITA>
	<ENG>ORDER NUM.</ENG>
	<ESP>ORDER NUM.</ESP>
	<DEU>ORDER NUM.</DEU>
	<FRA>ORDER NUM.</FRA>
<Orig_str>NUM. COMMESSA</Orig_str>
	<ITA>NUM. COMMESSA</ITA>
	<ENG>MASTER ORDER NUM.</ENG>
	<ESP>MASTER ORDER NUM.</ESP>
	<DEU>MASTER ORDER NUM.</DEU>
	<FRA>MASTER ORDER NUM.</FRA>
<Orig_str>RIF. ORDINE CLIENTE</Orig_str>
	<ITA>RIF. ORDINE CLIENTE</ITA>
	<ENG>CUSTOMER ORDER REF.</ENG>
	<ESP>CUSTOMER ORDER REF.</ESP>
	<DEU>CUSTOMER ORDER REF.</DEU>
	<FRA>CUSTOMER ORDER REF.</FRA>
<Orig_str>CLIENTE</Orig_str>
	<ITA>CLIENTE</ITA>
	<ENG>CUSTOMER</ENG>
	<ESP>CUSTOMER</ESP>
	<DEU>CUSTOMER</DEU>
	<FRA>CUSTOMER</FRA>
<Orig_str>Cliente</Orig_str>
	<ITA>Cliente</ITA>
	<ENG>Customer</ENG>
	<ESP>Customer</ESP>
	<DEU>Customer</DEU>
	<FRA>Customer</FRA>
<Orig_str>AGENTE</Orig_str>
    <ITA>AGENTE</ITA>
    <ENG>SALES RAPRESENTATIVE</ENG>
    <ESP>AGENT</ESP>
    <FRA>AGENT</FRA>
    <DEU>AGENT DEU</DEU>
<Orig_str>Agente</Orig_str>
    <ITA>Agente</ITA>
    <ENG>Sales rapresentative</ENG>
    <ESP>Agent</ESP>
    <FRA>Agent</FRA>
    <DEU>Agent DEU</DEU>
<Orig_str>Ricerca in corso ...</Orig_str>
	<ITA>Ricerca in corso ...</ITA>
	<ENG>Searching ...</ENG>
	<ESP>Searching ...</ESP>
	<DEU>Searching ...</DEU>
	<FRA>Searching ...</FRA>
<Orig_str>Data conferma ordine dal</Orig_str>
	<ITA>Data conferma ordine dal</ITA>
	<ENG>Order confirm date from</ENG>
	<ESP>Order confirm date from</ESP>
	<DEU>Order confirm date from</DEU>
	<FRA>Order confirm date from</FRA>
<Orig_str>Agente senza AreaManager</Orig_str>
	<ITA>Agente senza AreaManager</ITA>
	<ENG>Agent without AreaManager</ENG>
	<ESP>Agent without AreaManager</ESP>
	<DEU>Agent without AreaManager</DEU>
	<FRA>Agent without AreaManager</FRA>
<Orig_str>AreaManager</Orig_str>
	<ITA>AreaManager</ITA>
	<ENG>AreaManager</ENG>
	<ESP>AreaManager</ESP>
	<DEU>AreaManager</DEU>
	<FRA>AreaManager</FRA>
<Orig_str>BACHECA</Orig_str>
	<ITA>BACHECA</ITA>
	<ENG>SHOWCASE</ENG>
	<ESP>SHOWCASE</ESP>
	<DEU>SHOWCASE</DEU>
	<FRA>SHOWCASE</FRA>
<Orig_str>Verifica rapida portate</Orig_str>
	<ITA>Verifica rapida portate</ITA>
	<ENG>Quick loading capacity</ENG>
	<ESP>Quick loading capacity</ESP>
	<DEU>Quick loading capacity</DEU>
	<FRA>Quick loading capacity</FRA>
<Orig_str>Avanzamento Ordini</Orig_str>
	<ITA>Avanzamento Ordini</ITA>
	<ENG>Orders advance</ENG>
	<ESP>Orders advance</ESP>
	<DEU>Orders advance</DEU>
	<FRA>Orders advance</FRA>
<Orig_str>IN COMMERCIALE</Orig_str>
	<ITA>IN COMMERCIALE</ITA>
	<ENG>SALES</ENG>
	<ESP>SALES</ESP>
	<DEU>SALES</DEU>
	<FRA>SALES</FRA>
<Orig_str>IN UFFICIO TECNICO</Orig_str>
	<ITA>IN UFFICIO TECNICO</ITA>
	<ENG>TECHNICAL OFFICE</ENG>
	<ESP>TECHNICAL OFFICE</ESP>
	<DEU>TECHNICAL OFFICE</DEU>
	<FRA>TECHNICAL OFFICE</FRA>
<Orig_str>IN CONTROLLO</Orig_str>
	<ITA>IN CONTROLLO</ITA>
	<ENG>CONTROL</ENG>
	<ESP>CONTROL</ESP>
	<DEU>CONTROL</DEU>
	<FRA>CONTROL</FRA>
<Orig_str>IN PRODUZIONE</Orig_str>
	<ITA>IN PRODUZIONE</ITA>
	<ENG>PRODUCTION</ENG>
	<ESP>PRODUCTION</ESP>
	<DEU>PRODUCTION</DEU>
	<FRA>PRODUCTION</FRA>
<Orig_str>PRONTO PARZIALE</Orig_str>
	<ITA>PRONTO PARZIALE</ITA>
	<ENG>PARTIAL READY</ENG>
	<ESP>PARTIAL READY</ESP>
	<DEU>PARTIAL READY</DEU>
	<FRA>PARTIAL READY</FRA>
<Orig_str>PRONTO</Orig_str>
	<ITA>PRONTO</ITA>
	<ENG>READY</ENG>
	<ESP>READY</ESP>
	<DEU>READY</DEU>
	<FRA>READY</FRA>
<Orig_str>Cruscotto</Orig_str>
	<ITA>Cruscotto</ITA>
	<ENG>Dashboard</ENG>
	<ESP>Dashboard</ESP>
	<DEU>Dashboard</DEU>
	<FRA>Dashboard</FRA>
<Orig_str>Ver.Portate</Orig_str>
	<ITA>Ver.Portate</ITA>
	<ENG>Capacity check</ENG>
	<ESP>Capacity check</ESP>
	<DEU>Capacity check</DEU>
	<FRA>Capacity check</FRA>
<Orig_str>NewItem</Orig_str>
	<ITA>Nuovo Articolo</ITA>
	<ENG>New Item</ENG>
	<ESP>New Item</ESP>
	<DEU>New Item</DEU>
	<FRA>New Item</FRA>
<Orig_str>Avanz.Ordini</Orig_str>
	<ITA>Avanz.Ordini</ITA>
	<ENG>Orders advance</ENG>
	<ESP>Orders advance</ESP>
	<DEU>Orders advance</DEU>
	<FRA>Orders advance</FRA>
<Orig_str>Stat.Off</Orig_str>
	<ITA>Stat.Off</ITA>
	<ENG>Off.Stat</ENG>
	<ESP>Off.Stat</ESP>
	<DEU>Off.Stat</DEU>
	<FRA>Off.Stat</FRA>
<Orig_str>Stat.Ord</Orig_str>
	<ITA>Stat.Ord</ITA>
	<ENG>Ord.Stat</ENG>
	<ESP>Ord.Stat</ESP>
	<DEU>Ord.Stat</DEU>
	<FRA>Ord.Stat</FRA>
<Orig_str>Ass.Off</Orig_str>
	<ITA>Ass.Off</ITA>
	<ENG>Off.Ass</ENG>
	<ESP>Off.Ass</ESP>
	<DEU>Off.Ass</DEU>
	<FRA>Off.Ass</FRA>
<Orig_str>Ass.Ord</Orig_str>
	<ITA>Ass.Ord</ITA>
	<ENG>Ord.Ass</ENG>
	<ESP>Ord.Ass</ESP>
	<DEU>Ord.Ass</DEU>
	<FRA>Ord.Ass</FRA>
<Orig_str>Statistiche Offerte</Orig_str>
	<ITA>Statistiche Offerte</ITA>
	<ENG>Offers Statistics</ENG>
	<ESP>Offers Statistics</ESP>
	<DEU>Offers Statistics</DEU>
	<FRA>Offers Statistics</FRA>
<Orig_str>Statistiche Ordini</Orig_str>
	<ITA>Statistiche Ordini</ITA>
	<ENG>Orders Statistics</ENG>
	<ESP>Orders Statistics</ESP>
	<DEU>Orders Statistics</DEU>
	<FRA>Orders Statistics</FRA>
<Orig_str>Altezza (m)</Orig_str>
	<ITA>Altezza (m)</ITA>
	<ENG>Height (m)</ENG>
	<ESP>Height (m)</ESP>
	<DEU>Height (m)</DEU>
	<FRA>Height (m)</FRA>
<Orig_str>Peso (kg)</Orig_str>
	<ITA>Peso (kg)</ITA>
	<ENG>Weight (Kg)</ENG>
	<ESP>Weight (Kg)</ESP>
	<DEU>Weight (Kg)</DEU>
	<FRA>Weight (Kg)</FRA>
<Orig_str>Lunghezza (m)</Orig_str>
	<ITA>Lunghezza (m)</ITA>
	<ENG>Lenght (m)</ENG>
	<ESP>Lenght (m)</ESP>
	<DEU>Lenght (m)</DEU>
	<FRA>Lenght (m)</FRA>
<Orig_str>Profondità (m)</Orig_str>
	<ITA>Profondità (m)</ITA>
	<ENG>Depth (m)</ENG>
	<ESP>Depth (m)</ESP>
	<DEU>Depth (m)</DEU>
	<FRA>Depth (m)</FRA>
<Orig_str>Miei Agenti</Orig_str>
	<ITA>Miei Agenti</ITA>
	<ENG>My Agents</ENG>
	<ESP>My Agents</ESP>
	<DEU>My Agents</DEU>
	<FRA>My Agents</FRA>
<Orig_str>Agenti senza AM</Orig_str>
	<ITA>Agenti senza AM</ITA>
	<ENG>Agents without AM</ENG>
	<ESP>Agents without AM</ESP>
	<DEU>Agents without AM</DEU>
	<FRA>Agents without AM</FRA>
<Orig_str>Cruscotto Trattative</Orig_str>
	<ITA>Cruscotto Trattative</ITA>
	<ENG>Negotiations Dashboard</ENG>
	<ESP>Negotiations Dashboard</ESP>
	<DEU>Negotiations Dashboard</DEU>
	<FRA>Negotiations Dashboard</FRA>
<Orig_str>Cruscotto Offerte</Orig_str>
	<ITA>Cruscotto Offerte</ITA>
	<ENG>Offers Dashboard</ENG>
	<ESP>Offers Dashboard</ESP>
	<DEU>Offers Dashboard</DEU>
	<FRA>Offers Dashboard</FRA>
<Orig_str>Cruscotto Ordini</Orig_str>
	<ITA>Cruscotto Ordini</ITA>
	<ENG>Orders Dashboard</ENG>
	<ESP>Orders Dashboard</ESP>
	<DEU>Orders Dashboard</DEU>
	<FRA>Orders Dashboard</FRA>
<Orig_str>Cruscotto Ordinato</Orig_str>
	<ITA>Cruscotto Ordinato</ITA>
	<ENG>Orders Dashboard</ENG>
	<ESP>Orders Dashboard</ESP>
	<DEU>Orders Dashboard</DEU>
	<FRA>Orders Dashboard</FRA>	
<Orig_str>Terzi</Orig_str>
	<ITA>Terzi</ITA>
	<ENG>Third</ENG>
	<ESP>Third</ESP>
	<DEU>Third</DEU>
	<FRA>Third</FRA>
<Orig_str>Dettaglio Stato</Orig_str>
	<ITA>Dettaglio Stato</ITA>
	<ENG>Status Detail</ENG>
	<ESP>Status Detail</ESP>
	<DEU>Status Detail</DEU>
	<FRA>Status Detail</FRA>
<Orig_str>Trattativa</Orig_str>
	<ITA>Trattativa</ITA>
	<ENG>Negotiation</ENG>
	<ESP>Negotiation</ESP>
	<DEU>Negotiation</DEU>
	<FRA>Negotiation</FRA>
<Orig_str>Cliente/Prospect</Orig_str>
	<ITA>Cliente/Prospect</ITA>
	<ENG>Customer/Prospect</ENG>
	<ESP>Customer/Prospect</ESP>
	<DEU>Customer/Prospect</DEU>
	<FRA>Customer/Prospect</FRA>
<Orig_str>Tipo Trt</Orig_str>
	<ITA>Tipo Trt</ITA>
	<ENG>Neg type</ENG>
	<ESP>Neg type</ESP>
	<DEU>Neg type</DEU>
	<FRA>Neg type</FRA>
<Orig_str>Tipo Off</Orig_str>
	<ITA>Tipo Off</ITA>
	<ENG>Off type</ENG>
	<ESP>Off type</ESP>
	<DEU>Off type</DEU>
	<FRA>Off type</FRA>
<Orig_str>Tipo Ord</Orig_str>
	<ITA>Tipo Ord</ITA>
	<ENG>Ord type</ENG>
	<ESP>Ord type</ESP>
	<DEU>Ord type</DEU>
	<FRA>Ord type</FRA>	
<Orig_str>Tappa</Orig_str>
	<ITA>Tappa</ITA>
	<ENG>Phase</ENG>
	<ESP>Phase</ESP>
	<DEU>Phase</DEU>
	<FRA>Phase</FRA>
<Orig_str>N. Offerte</Orig_str>
	<ITA>N. Offerte</ITA>
	<ENG>N. Offers</ENG>
	<ESP>N. Offers</ESP>
	<DEU>N. Offers</DEU>
	<FRA>N. Offers</FRA>
<Orig_str>Prev. Chiusura</Orig_str>
	<ITA>Prev. Chiusura</ITA>
	<ENG>Close prev.</ENG>
	<ESP>Close prev.</ESP>
	<DEU>Close prev.</DEU>
	<FRA>Close prev.</FRA>
<Orig_str>Importo</Orig_str>
	<ITA>Importo</ITA>
	<ENG>Amount</ENG>
	<ESP>Amount</ESP>
	<DEU>Amount</DEU>
	<FRA>Amount</FRA>
<Orig_str>Vita</Orig_str>
	<ITA>Vita</ITA>
	<ENG>Life</ENG>
	<ESP>Life</ESP>
	<DEU>Life</DEU>
	<FRA>Life</FRA>
<Orig_str>Imp. Ponderato</Orig_str>
	<ITA>Imp. Ponderato</ITA>
	<ENG>Average am.</ENG>
	<ESP>Average am.</ESP>
	<DEU>Average am.</DEU>
	<FRA>Average am.</FRA>
<Orig_str>Importo netto</Orig_str>
	<ITA>Importo netto</ITA>
	<ENG>Net amount</ENG>
	<ESP>Net amount</ESP>
	<DEU>Net amount</DEU>
	<FRA>Net amount</FRA>
<Orig_str>Importo lordo materiali</Orig_str>
	<ITA>Importo lordo materiali</ITA>
	<ENG>Gross material amount</ENG>
	<ESP>Gross material amount</ESP>
	<DEU>Gross material amount</DEU>
	<FRA>Gross material amount</FRA>
<Orig_str>Nuova Trattativa</Orig_str>
	<ITA>Nuova Trattativa</ITA>
	<ENG>New Negotiation</ENG>
	<ESP>New Negotiation</ESP>
	<DEU>New Negotiation</DEU>
	<FRA>New Negotiation</FRA>
<Orig_str>Configura Trattativa</Orig_str>
	<ITA>Configura Trattativa</ITA>
	<ENG>Configure Negotiation</ENG>
	<ESP>Configure Negotiation</ESP>
	<DEU>Configure Negotiation</DEU>
	<FRA>Configure Negotiation</FRA>
<Orig_str>Tipo Ordine</Orig_str>
	<ITA>Tipo Ordine</ITA>
	<ENG>Order Type</ENG>
	<ESP>Order Type</ESP>
	<DEU>Order Type</DEU>
	<FRA>Order Type</FRA>
<Orig_str>Data consegna</Orig_str>
	<ITA>Data consegna</ITA>
	<ENG>Delivery date</ENG>
	<ESP>Delivery date</ESP>
	<DEU>Delivery date</DEU>
	<FRA>Delivery date</FRA>
<Orig_str>Attive</Orig_str>
	<ITA>Attive</ITA>
	<ENG>Active</ENG>
	<ESP>Active</ESP>
	<DEU>Active</DEU>
	<FRA>Active</FRA>
<Orig_str>Sospese</Orig_str>
	<ITA>Sospese</ITA>
	<ENG>Suspended</ENG>
	<ESP>Suspended</ESP>
	<DEU>Suspended</DEU>
	<FRA>Suspended</FRA>
<Orig_str>Chiuse</Orig_str>
	<ITA>Chiuse</ITA>
	<ENG>Closed</ENG>
	<ESP>Closed</ESP>
	<DEU>Closed</DEU>
	<FRA>Closed</FRA>
<Orig_str>Fine Stimata</Orig_str>
	<ITA>Fine Stimata</ITA>
	<ENG>Estimated End</ENG>
	<ESP>Estimated End</ESP>
	<DEU>Estimated End</DEU>
	<FRA>Estimated End</FRA>
<Orig_str>Ore Stimate</Orig_str>
	<ITA>Ore Stimate</ITA>
	<ENG>Estimated Hours</ENG>
	<ESP>Estimated Hours</ESP>
	<DEU>Estimated Hours</DEU>
	<FRA>Estimated Hours</FRA>
<Orig_str>Modifica Multi-Fase</Orig_str>
	<ITA>Modifica Multi-Fase</ITA>
	<ENG>Multi-Phase Modify</ENG>
	<ESP>Multi-Phase Modify</ESP>
	<DEU>Multi-Phase Modify</DEU>
	<FRA>Multi-Phase Modify</FRA>
<Orig_str>Modifica Multi-Attivià</Orig_str>
	<ITA>Modifica Multi-Attivià</ITA>
	<ENG>Multi-Activity Modify</ENG>
	<ESP>Multi-Activity Modify</ESP>
	<DEU>Multi-Activity Modify</DEU>
	<FRA>Multi-Activity Modify</FRA>
<Orig_str><![CDATA[Numero di Commesse per utente per anno di esame.<BR>Variazione del numero di Commesse del Anno sul Anno Precedente.]]></Orig_str>
	<ITA><![CDATA[Numero di Commesse per utente per anno di esame.<BR>Variazione del numero di Commesse del Anno sul Anno Precedente.]]></ITA>
	<ENG><![CDATA[Number of Orders for user of year.<BR>Change of number of Orders of Year on Previous Year.]]></ENG>
	<ESP><![CDATA[Number of Orders for user of year.<BR>Change of number of Orders of Year on Previous Year.]]></ESP>
	<DEU><![CDATA[Number of Orders for user of year.<BR>Change of number of Orders of Year on Previous Year.]]></DEU>
	<FRA><![CDATA[Number of Orders for user of year.<BR>Change of number of Orders of Year on Previous Year.]]></FRA>
<Orig_str><![CDATA[Valore Totale delle Commesse per utente per anno di esame.<BR>Variazione del Valore Totale delle Commesse del Anno sul Anno Precedente.]]></Orig_str>
	<ITA><![CDATA[Valore Totale delle Commesse per utente per anno di esame.<BR>Variazione del Valore Totale delle Commesse del Anno sul Anno Precedente.]]></ITA>
	<ENG><![CDATA[Total Value of Orders for user for year.<BR>Change of Total Value of Orders of Year on Previous Year.]]></ENG>
	<ESP><![CDATA[Total Value of Orders for user for year.<BR>Change of Total Value of Orders of Year on Previous Year.]]></ESP>
	<DEU><![CDATA[Total Value of Orders for user for year.<BR>Change of Total Value of Orders of Year on Previous Year.]]></DEU>
	<FRA><![CDATA[Total Value of Orders for user for year.<BR>Change of Total Value of Orders of Year on Previous Year.]]></FRA>
<Orig_str><![CDATA[Valore Parziale ad Oggi delle Commesse per utente per anno di esame.<BR>Variazione del Valore ad Oggi delle Commesse del Anno sul Anno Precedente.]]></Orig_str>
	<ITA><![CDATA[Valore Parziale ad Oggi delle Commesse per utente per anno di esame.<BR>Variazione del Valore ad Oggi delle Commesse del Anno sul Anno Precedente.]]></ITA>
	<ENG><![CDATA[Partial Value Today of Orders for user for year.<BR>Change of Value Today of Orders for Year on Previous Year.]]></ENG>
	<ESP><![CDATA[Partial Value Today of Orders for user for year.<BR>Change of Value Today of Orders for Year on Previous Year.]]></ESP>
	<DEU><![CDATA[Partial Value Today of Orders for user for year.<BR>Change of Value Today of Orders for Year on Previous Year.]]></DEU>
	<FRA><![CDATA[Partial Value Today of Orders for user for year.<BR>Change of Value Today of Orders for Year on Previous Year.]]></FRA>
<Orig_str>Vita</Orig_str>
	<ITA>Vita</ITA>
	<ENG>Life</ENG>
	<ESP>Life</ESP>
	<DEU>Life</DEU>
	<FRA>Life</FRA>
<Orig_str>Mostra Offerte</Orig_str>
	<ITA>Mostra Offerte</ITA>
	<ENG>Show Offers</ENG>
	<ESP>Show Offers</ESP>
	<DEU>Show Offers</DEU>
	<FRA>Show Offers</FRA>
<Orig_str>Mostra Ordini</Orig_str>
	<ITA>Mostra Ordini</ITA>
	<ENG>Show Orders</ENG>
	<ESP>Show Orders</ESP>
	<DEU>Show Orders</DEU>
	<FRA>Show Orders</FRA>
<Orig_str>Data Fine Attività</Orig_str>
	<ITA>Data Fine Attività</ITA>
	<ENG>End Task Date</ENG>
	<ESP>End Task Date</ESP>
	<DEU>End Task Date</DEU>
	<FRA>End Task Date</FRA>
<Orig_str>Data Fine Fase</Orig_str>
	<ITA>Data Fine Fase</ITA>
	<ENG>End Phase Date</ENG>
	<ESP>End Phase Date</ESP>
	<DEU>End Phase Date</DEU>
	<FRA>End Phase Date</FRA>
<Orig_str>Completata con fasi aperte</Orig_str>
	<ITA>Completata con fasi aperte</ITA>
	<ENG>Completed with open phases</ENG>
	<ESP>Completed with open phases</ESP>
	<DEU>Completed with open phases</DEU>
	<FRA>Completed with open phases</FRA>
<Orig_str>N° Offerta/Ordine</Orig_str>
	<ITA>N° Offerta/Ordine</ITA>
	<ENG>N° Offer/Order</ENG>
	<ESP>N° Offer/Order</ESP>
	<DEU>N° Offer/Order</DEU>
	<FRA>N° Offer/Order</FRA>
<Orig_str>Progetti da assegnare</Orig_str>
	<ITA>Progetti da assegnare</ITA>
	<ENG>Projects to assign</ENG>
	<ESP>Projects to assign</ESP>
	<DEU>Projects to assign</DEU>
	<FRA>Projects to assign</FRA>
<Orig_str>PROGETTI DA ASSEGNARE</Orig_str>
	<ITA>PROGETTI DA ASSEGNARE</ITA>
	<ENG>PROJECTS TO ASSIGN</ENG>
	<ESP>PROJECTS TO ASSIGN</ESP>
	<DEU>PROJECTS TO ASSIGN</DEU>
	<FRA>PROJECTS TO ASSIGN</FRA>
<Orig_str>Gantt Offerte</Orig_str>
	<ITA>Gantt Offerte</ITA>
	<ENG>Gantt Offers</ENG>
	<ESP>Gantt Offers</ESP>
	<DEU>Gantt Offers</DEU>
	<FRA>Gantt Offers</FRA>
<Orig_str>Gantt Ordini</Orig_str>
	<ITA>Gantt Ordini</ITA>
	<ENG>Gantt Orders</ENG>
	<ESP>Gantt Orders</ESP>
	<DEU>Gantt Orders</DEU>
	<FRA>Gantt Orders</FRA>
<Orig_str>Flusso proposto</Orig_str>
	<ITA>Flusso proposto</ITA>
	<ENG>Proposed flow</ENG>
	<ESP>Proposed flow</ESP>
	<DEU>Proposed flow</DEU>
	<FRA>Proposed flow</FRA>
<Orig_str>Descrizione progetto</Orig_str>
	<ITA>Descrizione progetto</ITA>
	<ENG>Project description</ENG>
	<ESP>Project description</ESP>
	<DEU>Project description</DEU>
	<FRA>Project description</FRA>
<Orig_str>Tempi Consegna ODV</Orig_str>
	<ITA>Tempi Consegna ODV</ITA>
	<ENG>Order Delivery Time</ENG>
	<ESP>Order Delivery Time</ESP>
	<DEU>Order Delivery Time</DEU>
	<FRA>Order Delivery Time</FRA>
<Orig_str>Scarico Ore</Orig_str>
	<ITA>Scarico Ore</ITA>
	<ENG>Hour release</ENG>
	<ESP>Hour release</ESP>
	<DEU>Hour release</DEU>
	<FRA>Hour release</FRA>
<Orig_str>Verifica portate</Orig_str>
	<ITA>Verifica portate</ITA>
	<ENG>Quick loading capacity</ENG>
	<ESP>Quick loading capacity</ESP>
	<DEU>Quick loading capacity</DEU>
	<FRA>Quick loading capacity</FRA>
<Orig_str>Commesse</Orig_str>
	<ITA>Commesse</ITA>
	<ENG>Master Orders</ENG>
	<ESP>Master Orders</ESP>
	<DEU>Master Orders</DEU>
	<FRA>Master Orders</FRA>
<Orig_str>Tipo Commessa</Orig_str>
	<ITA>Tipo Commessa</ITA>
	<ENG>Master Order Type</ENG>
	<ESP>Master Order Type</ESP>
	<DEU>Master Order Type</DEU>
	<FRA>Master Order Type</FRA>
<Orig_str>Prezzo service</Orig_str>
	<ITA>Prezzo service</ITA>
	<ENG>Service price</ENG>
	<ESP>Service price</ESP>
	<DEU>Service price</DEU>
	<FRA>Service price</FRA>


	
	
	